# Configuration file for ChatCoPlus ${project.version} (https://github.com/zeroBzeroT/ChatCoPlus)
ChatCo:
  created: ${project.version}
  chatDisabled: false
  bStats: true
  chatToConsole: true
  toggleChatEnabled: true
  ignoresEnabled: true
  ignoreMessageEnabled: true
  chatDisabledMessageEnabled: true
  spoilersEnabled: false
  whisperChangesEnabled: true
  whisperOnClick: true
  newCommands: true
  replyCommands: true
  lastCommand: true
  whisperLog: false
  whisperMonitoring: false
  whisperFormat:
    receive: "%SENDER% whispers: "
    send: "To %RECEIVER%: "
    color: light_purple
  chatPrefixes:
    AQUA: null
    BLACK: null
    BLUE: null
    BOLD: null
    DARK_AQUA: null
    DARK_BLUE: null
    DARK_GRAY: null
    DARK_GREEN: null
    DARK_PURPLE: null
    DARK_RED: null
    GOLD: null
    GRAY: null
    GREEN: ">"
    ITALIC: null
    LIGHT_PURPLE: null
    MAGIC: null
    RED: null
    STRIKETHROUGH: null
    UNDERLINE: null
    WHITE: null
    YELLOW: null
  chatColors:
    AQUA: null
    BLACK: null
    BLUE: "`"
    BOLD: null
    DARK_AQUA: null
    DARK_BLUE: null
    DARK_GRAY: null
    DARK_GREEN: null
    DARK_PURPLE: null
    DARK_RED: null
    GOLD: null
    GRAY: null
    GREEN: null
    ITALIC: null
    LIGHT_PURPLE: null
    MAGIC: null
    RED: null
    STRIKETHROUGH: null
    UNDERLINE: null
    WHITE: null
    YELLOW: null